Repository datarobot/airflow-provider-datarobot, pull requests merged in 2025-02, with the labels that each got.

#122 [DM-16904] Add "recipe_id" optional parameter to `CreateProjectOperator`
  datarobot_provider/operators/datarobot.py
  requirements.txt
  tests/unit/operators/test_datarobot.py
Labels: 00 - Ready for Review

#128 [DM-16872] Add database wrangling into the demo DAG.
  CHANGES.md
  datarobot_provider/example_dags/hospital_readmissions_example.py
  datarobot_provider/operators/ai_catalog.py
  datarobot_provider/operators/datarobot.py
  pyproject.toml
  tests/unit/operators/test_datarobot.py
Labels: 00 - Ready for Review

#127 [DM-1903] Add CreateDatasetFromProjectOperator
  CHANGES.md
  datarobot_provider/operators/ai_catalog.py
  tests/unit/operators/test_ai_catalog.py
Labels: 00 - Ready for Review

#132 [MLDEV-1144] Add docs testing to main ci checks pipeline
  .harness/cichecks.yaml
  Makefile
  pyproject.toml
Labels: Needs Review: MLDev, 00 - Ready for Review

#131 [DM-16986] Introduce a `BaseDatarobotOperator`
  datarobot_provider/operators/ai_catalog.py
  datarobot_provider/operators/autopilot.py
  datarobot_provider/operators/base_datarobot_operator.py
  datarobot_provider/operators/bias_and_fairness.py
  datarobot_provider/operators/connections.py
  datarobot_provider/operators/credentials.py
  datarobot_provider/operators/custom_models.py
  datarobot_provider/operators/datarobot.py
  datarobot_provider/operators/deployment.py
  datarobot_provider/operators/feature_discovery.py
  tests/unit/operators/test_custom_models.py
Labels: Ready for Review

#134 [DM-16908] Better dag
  datarobot_provider/example_dags/hospital_readmissions_example.py
  datarobot_provider/operators/ai_catalog.py
  datarobot_provider/operators/datarobot.py
  tests/unit/operators/test_ai_catalog.py
  tests/unit/operators/test_datarobot.py
Labels: 00 - Ready for Review, Auto Merge when Ready

#145 [MLDEV-1216] Update existing templates and pipelines to allow both release and early-access
  .harness/build_and_publish_early_access_pypi.yaml
  .harness/input_sets/release_early_access_pypi.yaml
  .harness/release_early_access_pypi.yaml
  .harness/release_pypi.yaml
  .harness/templates/publish_early_access_to_pypi_or_testpypi.yaml
Labels: 00 - Ready for Review

#143 [DM-17020] Set upper limit on pip version (<24.1)
  Makefile
Labels: Ready for Review

#144 [DM-17022] Default use case
  datarobot_provider/example_dags/hospital_readmissions_example.py
  datarobot_provider/operators/ai_catalog.py
  datarobot_provider/operators/base_datarobot_operator.py
  datarobot_provider/operators/datarobot.py
  datarobot_provider/operators/feature_discovery.py
  tests/unit/conftest.py
  tests/unit/operators/test_ai_catalog.py
  tests/unit/operators/test_base_datarobot_operator.py
  tests/unit/operators/test_datarobot.py
Labels: 00 - Ready for Review

#136 [mmm-18320] operator create registered model registered model version
  CHANGES.md
  README.md
  datarobot_provider/operators/model_registry.py
  tests/unit/operators/test_model_registry.py
Labels: 00 - Ready for Review

#130 [MLDEV-1194] Create _experimental folder and move untested dags to this
  datarobot_provider/_experimental/__init__.py
  datarobot_provider/_experimental/example_dags/__init__.py
  datarobot_provider/_experimental/example_dags/advanced_datarobot_pipeline_jdbc_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_autopilot_options_pipeline_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_aws_s3_batch_scoring_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_azure_storage_batch_scoring_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_batch_monitoring_job_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_batch_scoring_templated_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_bigquery_batch_scoring_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_create_project_from_ai_catalog_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_create_project_from_dataset_version_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_custom_model_pipeline_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_custom_partitioning_pipeline_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_dataset_new_version_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_dataset_upload_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_datetime_partitioning_pipeline_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_external_model_pipeline_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_feature_discovery_pipeline_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_gcp_storage_batch_scoring_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_get_datastore_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_jdbc_batch_scoring_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_jdbc_dataset_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_jdbc_dynamic_dataset_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_pipeline_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_replace_custom_model_pipeline_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_score_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_timeseries_pipeline_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_upload_actuals_catalog_dag.py
  datarobot_provider/_experimental/example_dags/deployment_activate_deactivate_dag.py
  datarobot_provider/_experimental/example_dags/deployment_replace_model_dag.py
  datarobot_provider/_experimental/example_dags/deployment_service_stats_dag.py
  datarobot_provider/_experimental/example_dags/deployment_stat_and_accuracy_dag.py
  datarobot_provider/_experimental/example_dags/deployment_update_monitoring_settings_dag.py
  datarobot_provider/_experimental/example_dags/deployment_update_segment_analysis_settings_dag.py
  datarobot_provider/_experimental/example_dags/download_scoring_code_from_deployment_dag.py
  datarobot_provider/_experimental/example_dags/model_compute_insights_dag.py
  datarobot_provider/_experimental/example_dags/model_compute_prediction_explanations_dag.py
  datarobot_provider/_experimental/example_dags/model_compute_predictions_dag.py
  datarobot_provider/_experimental/example_dags/model_compute_shap_dag.py
  datarobot_provider/_experimental/example_dags/model_retrain_dag.py
  datarobot_provider/_experimental/example_dags/model_train_dag.py
  requirements.txt
  tests/unit/_experimental/__init__.py
  tests/unit/_experimental/dags/__init__.py
  tests/unit/_experimental/dags/conftest.py
  tests/unit/_experimental/dags/pipline/__init__.py
  tests/unit/_experimental/dags/pipline/test_datarobot_pipeline_dag.py
  tests/unit/_experimental/dags/predictions/__init__.py
  tests/unit/_experimental/dags/predictions/test_datarobot_azure_storage_batch_scoring_dag.py
  tests/unit/_experimental/dags/predictions/test_datarobot_gcp_storage_batch_scoring_dag.py
  tests/unit/_experimental/dags/predictions/test_datarobot_s3_batch_scoring_dag.py
  tests/unit/_experimental/dags/predictions/test_datarobot_score_dag.py
  tests/unit/_experimental/dags/project/__init__.py
  tests/unit/_experimental/dags/project/test_create_project_from_ai_catalog_dag.py
  tests/unit/_experimental/dags/project/test_create_project_from_dataset_version_dag.py
Labels: 00 - Ready for Review

#147 [MLDEV-1165] Remove requirements.txt from repo
  requirements.txt
Labels: 00 - Ready for Review

#146 [MLDEV-1220] Fix locations of deployment operators (refactor)
  CODEOWNERS
  datarobot_provider/_experimental/example_dags/advanced_datarobot_pipeline_jdbc_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_aws_s3_batch_scoring_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_azure_storage_batch_scoring_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_batch_scoring_templated_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_bigquery_batch_scoring_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_gcp_storage_batch_scoring_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_jdbc_batch_scoring_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_pipeline_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_score_dag.py
  datarobot_provider/operators/datarobot.py
  datarobot_provider/operators/deployment.py
  tests/unit/operators/test_datarobot.py
Labels: 00 - Ready for Review

#149 [DM-17021] Get catalogVersionId if not defined by users
  datarobot_provider/operators/feature_discovery.py
  tests/unit/operators/test_feature_discovery.py
Labels: 00 - Ready for Review

#151 [mmm-18537] add register model step and select best model to Hospital Readmissions dag
  datarobot_provider/example_dags/hospital_readmissions_example.py
  datarobot_provider/operators/datarobot.py
  datarobot_provider/operators/model_registry.py
  tests/unit/operators/test_datarobot.py
Labels: Needs Review: MLDev, 00 - Ready for Review

#152 [MLDEV-1175] Update packaging to only include `_experimental` when building early-access version of package
  setup.py
  setup_early_access.py
Labels: Ready for Review, Auto Merge on Green

#153 [DM-16975] [DM-17066] Bump DataRobot client to 3.6.2 and apply relevant changes to Feature Discovery workflow
  datarobot_provider/operators/feature_discovery.py
  setup.py
  tests/unit/operators/test_feature_discovery.py
Labels: Ready for Review

#150 [MLDEV-1102] Blueprint select operator and some refactors
  CHANGES.md
  datarobot_provider/operators/datarobot.py
  docs/autodoc/operators_datarobot.md
  docs/autodoc/operators_project_use_case.md
  tests/unit/operators/test_datarobot.py
Labels: 00 - Ready for Review

#157 [MLDEV-1224] Fix input param in example dataset
  datarobot_provider/example_dags/hospital_readmissions_example.py
Labels: 00 - Ready for Review

#158 [CFX-1590] Mypy rule updates and prompted related updates
  datarobot_provider/autogen/generate_operator.py
  datarobot_provider/hooks/credentials.py
  datarobot_provider/operators/ai_catalog.py
  datarobot_provider/operators/base_datarobot_operator.py
  datarobot_provider/operators/datarobot.py
  pyproject.toml
Labels: Ready for Review, Close Jira on Merge

#160 [MLDEV-1225] Update and tag version 0.1.0 for release to pypi with P0 example DAG
  .harness/release_pypi.yaml
  CHANGES.md
  datarobot_provider/__init__.py
  datarobot_provider/_version.py
Labels: Needs Review: MLDev, 00 - Ready for Review

#156 [DM-16905] Add Feature Discovery example DAG
  CHANGES.md
  datarobot_provider/example_dags/deprecated_dags/__init__.py
  datarobot_provider/example_dags/feature_discovery_example.py
  datarobot_provider/operators/datarobot.py
  datarobot_provider/operators/feature_discovery.py
  tests/unit/operators/test_datarobot.py
Labels: Ready for Review

#162 [CFX-1605] DR AF Provider - Remove declared python 3.13 support
  setup.py
  setup_early_access.py
Labels: Ready for Review, Close Jira on Merge

#163 [CFX-1606] Add more project URLs that show in pypi - importantly the bug tracker
  setup.py
Labels: Ready for Review, Close Jira on Merge

#164 [MLDEV-1228] Add xgboost version of hospitlal readmissions example dag
  CHANGES.md
  datarobot_provider/example_dags/deprecated_dags/__init__.py
  datarobot_provider/example_dags/hospital_readmissions_xgboost_example.py
  setup.py
Labels: 00 - Ready for Review

#166 [CFX-1510] Use constants where appropriate
  datarobot_provider/autogen/generate_operator.py
  datarobot_provider/constants.py
  datarobot_provider/hooks/datarobot.py
  datarobot_provider/operators/base_datarobot_operator.py
  datarobot_provider/operators/gen/modeljob/model_job_get_operator.py
  datarobot_provider/sensors/client.py
  datarobot_provider/sensors/datarobot.py
  datarobot_provider/sensors/model_insights.py
  datarobot_provider/sensors/monitoring_job.py
  tests/fixtures/whitelist_test_output.txt
  tests/unit/autogen/test_generate_operator.py
Labels: Ready for Review

#165 [CFX-1510] Move DR Notebooks example DAG and rename existing directory
  datarobot_provider/_experimental/deprecated_example_dags/__init__.py
  datarobot_provider/_experimental/deprecated_example_dags/advanced_datarobot_pipeline_jdbc_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_autopilot_options_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_aws_s3_batch_scoring_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_azure_storage_batch_scoring_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_batch_monitoring_job_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_batch_scoring_templated_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_bigquery_batch_scoring_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_create_project_from_ai_catalog_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_create_project_from_dataset_version_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_custom_model_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_custom_partitioning_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_dataset_new_version_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_dataset_upload_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_datetime_partitioning_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_external_model_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_feature_discovery_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_gcp_storage_batch_scoring_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_get_datastore_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_jdbc_batch_scoring_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_jdbc_dataset_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_jdbc_dynamic_dataset_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_replace_custom_model_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_score_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_timeseries_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_upload_actuals_catalog_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/deployment_activate_deactivate_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/deployment_replace_model_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/deployment_service_stats_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/deployment_stat_and_accuracy_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/deployment_update_monitoring_settings_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/deployment_update_segment_analysis_settings_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/download_scoring_code_from_deployment_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/model_compute_insights_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/model_compute_prediction_explanations_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/model_compute_predictions_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/model_compute_shap_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/model_retrain_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/model_train_dag.py
  datarobot_provider/_experimental/example_dags/datarobot_run_notebook.py
  tests/unit/_experimental/dags/conftest.py
  tests/unit/_experimental/dags/pipline/test_datarobot_pipeline_dag.py
  tests/unit/_experimental/dags/predictions/test_datarobot_azure_storage_batch_scoring_dag.py
  tests/unit/_experimental/dags/predictions/test_datarobot_gcp_storage_batch_scoring_dag.py
  tests/unit/_experimental/dags/predictions/test_datarobot_s3_batch_scoring_dag.py
  tests/unit/_experimental/dags/predictions/test_datarobot_score_dag.py
  tests/unit/_experimental/dags/project/test_create_project_from_ai_catalog_dag.py
  tests/unit/_experimental/dags/project/test_create_project_from_dataset_version_dag.py
Labels: Ready for Review

#168 [MMM-18649] concat date time to register model name
  datarobot_provider/example_dags/hospital_readmissions_example.py
Labels: 00 - Ready for Review

#169 [-] Add Read the Docs Config in Preparation for RTD Generation
  .readthedocs.yaml
Labels: Needs Review: MLDev, 00 - Ready for Review

#167 [MLDEV-1113] Add compute shap preview operator to airflow
  datarobot_provider/_experimental/deprecated_example_dags/model_compute_shap_dag.py
  datarobot_provider/operators/model_insights.py
  docs/autodoc/operators_insights.md
  tests/unit/operators/test_model_insights_job.py
Labels: 00 - Ready for Review

#170 [MLDEV-1232] Update docs template
  .readthedocs.yaml
  setup.py
Labels: Needs Review: MLDev, 00 - Ready for Review

#171 [MLDEV-1233] Update readme with docs links and pypi
  README.md
  setup.py
Labels: 00 - Ready for Review

#161 [DM-17115] Remove use of `use_feature_discovery` as input
  datarobot_provider/operators/datarobot.py
Labels: Ready for Review

#173 [MLDEV-1239] Update release pipelines for pypi and early-access pypi to have valid tokens
  .harness/build_and_publish_early_access_pypi.yaml
  .harness/release_early_access_pypi.yaml
  .harness/release_pypi.yaml
  .harness/templates/publish_early_access_to_pypi_or_testpypi.yaml
Labels: 00 - Ready for Review

#172 [MLDEV-1235] Add documentation for first example dag
  CODEOWNERS
  docs/examples/hospital_readmissions_example.md
  docs/examples/index.md
  docs/index.md
  docs/reference/index.md
Labels: 00 - Ready for Review

#174 [MLDEV-1231] Add insights and model sensor to example P0 DAG #1
  datarobot_provider/example_dags/hospital_readmissions_xgboost_example.py
  datarobot_provider/operators/datarobot.py
  datarobot_provider/operators/model_insights.py
  tests/unit/operators/test_model_insights_job.py
Labels: 00 - Ready for Review

#177 [MMM-18684] p0 dag 2 deployment from registered model version implementation of first deployment step
  datarobot_provider/example_dags/hospital_readmissions_deployment_prediction_generation.py
  datarobot_provider/operators/deployment.py
  datarobot_provider/operators/monitoring.py
  tests/unit/operators/test_deployment.py
  tests/unit/operators/test_monitoring.py
Labels: 00 - Ready for Review

#179 [MLDEV-1243] Add deployment predictions dataset upload and scoring to example DAG
  datarobot_provider/example_dags/hospital_readmissions_deployment_prediction_generation.py
  datarobot_provider/example_dags/hospital_readmissions_xgboost_example.py
  datarobot_provider/example_dags/wrangler_example_recipe.py
Labels: 00 - Ready for Review
