Repository datarobot/airflow-provider-datarobot, pull requests merged in 2025-04, with the labels that each got.

#231 [MODEL-18594] Update README.md
  README.md
  datarobot_provider/operators/data_prep.py
  setup.py
  tests/unit/operators/test_data_prep.py
Labels: 00 - Ready for Review, Close Jira on Merge

#232 [RELEASE] Bump release for v0.5.0
  CHANGES.md
  datarobot_provider/__init__.py
  datarobot_provider/_version.py
Labels: Ready for Review, Auto Merge when Ready

#229 [MMM-18326]: implement operator to upload actuals
  datarobot_provider/operators/mlops.py
  tests/unit/operators/test_mlops.py
Labels: Ready for Review

#233 [RELEASE] Bump release for v1.0.0
  CHANGES.md
  datarobot_provider/__init__.py
  datarobot_provider/_version.py
Labels: Auto Merge on Green
