Repository datarobot/airflow-provider-datarobot, pull requests merged in 2025-05, with the labels that each got.

#234 [DM-17544] Support dynamic secondary dataset in feature discovery DAG
  CHANGES.md
  datarobot_provider/__init__.py
  datarobot_provider/_version.py
  datarobot_provider/example_dags/feature_discovery_retraining_and_scoring.py
  datarobot_provider/operators/base_datarobot_operator.py
  datarobot_provider/operators/data_registry.py
  setup.py
  tests/unit/operators/test_data_registry.py
Labels: 00 - Ready for Review

#235 [-] Set ceiling for apache-airflow to avoid breaking changes
  setup_early_access.py
Labels: Ready for Review, Needs Review: CFX, Needs Review: Predictive AI

#238 [CFX-2798] Account for renaming of method in experimental DR Python Client
  datarobot_provider/_experimental/operators/notebook.py
Labels: Ready for Review
