Repository datarobot/airflow-provider-datarobot, pull requests merged in 2025-03, with the labels that each got.

#180 [MODEL-18026] Fix P0 Dag 2 for release
  datarobot_provider/example_dags/hospital_readmissions_deployment_prediction_generation.py
Labels: 00 - Ready for Review

#182 [MODEL-17045][MODEL-17046][MODEL-17053] Cleanup feature impact/effects docstrings and shap impact operator
  CHANGES.md
  datarobot_provider/__init__.py
  datarobot_provider/_version.py
  datarobot_provider/operators/model_insights.py
  docs/autodoc/operators_insights.md
  tests/unit/operators/test_model_insights_job.py
Labels: 00 - Ready for Review

#176 [MODEL-17080] Add StatusCheck Sensor and cleanup related docs
  Makefile
  datarobot_provider/sensors/datarobot.py
  datarobot_provider/sensors/model_insights.py
  datarobot_provider/sensors/model_training.py
  datarobot_provider/sensors/monitoring_job.py
  docs/autodoc/api_reference.md
  docs/autodoc_operators/api_reference.md
  docs/autodoc_operators/operators_ai_catalog.md
  docs/autodoc_operators/operators_autopilot.md
  docs/autodoc_operators/operators_bias_and_fairness.md
  docs/autodoc_operators/operators_connections.md
  docs/autodoc_operators/operators_feature_discovery.md
  docs/autodoc_operators/operators_insights.md
  docs/autodoc_operators/operators_project_use_case.md
  docs/autodoc_sensors/api_reference.md
  docs/autodoc_sensors/sensors_datarobot.md
  docs/autodoc_sensors/sensors_jobs.md
  docs/index.md
  setup.py
  tests/unit/sensors/test_datarobot.py
Labels: 00 - Ready for Review

#185 [MODEL-18049] Update Early Access and Release pipelines to be more streamlined
  .harness/cichecks.yaml
  .harness/release_early_access_pypi.yaml
  .harness/release_pypi.yaml
  .harness/templates/unit_tests.yaml
Labels: 00 - Ready for Review

#186 [MODEL-18051] Add early access harness cron trigger to repo
  .harness/release_early_access_trigger.yaml
Labels: 00 - Ready for Review

#183 [PRED-11014] Adding predictions generation operators and sensor
  datarobot_provider/operators/predictions.py
  datarobot_provider/sensors/predictions.py
  docs/autodoc_operators/operators_predictions.md
  docs/autodoc_sensors/sensors_predictions.md
Labels: 00 - Ready for Review

#189 [MODEL-18068] Fix some tests that don't work right on latest mac dev env
  tests/unit/operators/test_custom_models.py
  tests/unit/operators/test_deployment.py
  tests/unit/operators/test_model_retraining.py
  tests/unit/operators/test_model_training.py
Labels: 00 - Ready for Review

#187 [MODEL-17067][MODEL-17068] Add OTV and Time Series start autopilot operator
  datarobot_provider/operators/autopilot.py
  tests/unit/operators/test_autopilot.py
Labels: 00 - Ready for Review

#188 [MMM-18323] operator replace the model
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_replace_custom_model_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/deployment_replace_model_dag.py
  datarobot_provider/operators/deployment.py
  tests/unit/operators/test_deployment.py
Labels: 00 - Ready for Review

#192 [MODEL-17041] Add get roc curve operator
  datarobot_provider/operators/model_insights.py
  docs/autodoc_operators/operators_insights.md
  tests/unit/operators/test_model_insights_job.py
Labels: 00 - Ready for Review

#190 [DM-17363] DB data prep
  datarobot_provider/example_dags/model_training_xgboost.py
  datarobot_provider/operators/ai_catalog.py
  tests/unit/operators/test_ai_catalog.py
Labels: Ready for Review

#196 [DM-17118] Remove outdated operators.
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_feature_discovery_pipeline_dag.py
  datarobot_provider/operators/feature_discovery.py
  tests/unit/operators/test_feature_discovery.py
Labels: Ready for Review

#195 [MODEL-17051] Update docstrings to Google Docstring format for datarobot operators
  datarobot_provider/operators/datarobot.py
  docs/autodoc_operators/operators_project_use_case.md
Labels: 00 - Ready for Review

#194 [MODEL-17073] Add residuals operator, tests, and docs
  datarobot_provider/operators/model_insights.py
  docs/autodoc_operators/operators_insights.md
  tests/unit/operators/test_model_insights_job.py
Labels: 00 - Ready for Review

#198 [MODEL-18215] Update codeowners to point to predictive-ai instead of MLDEV
  CODEOWNERS
Labels: 00 - Ready for Review

#202 [MODEL-17050] Operator to return a list of ids and type for all trained models in project
  datarobot_provider/operators/datarobot.py
  docs/autodoc_operators/operators_project_use_case.md
  tests/unit/operators/test_datarobot.py
Labels: 00 - Ready for Review

#201 [DM-17450] Remove credentials management.
  README.md
  datarobot_provider/__init__.py
  datarobot_provider/_experimental/deprecated_example_dags/advanced_datarobot_pipeline_jdbc_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_aws_s3_batch_scoring_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_azure_storage_batch_scoring_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_batch_monitoring_job_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_bigquery_batch_scoring_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_dataset_new_version_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_gcp_storage_batch_scoring_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_get_datastore_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_jdbc_batch_scoring_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_jdbc_dataset_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_jdbc_dynamic_dataset_dag.py
  datarobot_provider/hooks/connections.py
  datarobot_provider/hooks/credentials.py
  datarobot_provider/operators/ai_catalog.py
  datarobot_provider/operators/connections.py
  datarobot_provider/operators/credentials.py
  tests/unit/_experimental/dags/predictions/test_datarobot_azure_storage_batch_scoring_dag.py
  tests/unit/_experimental/dags/predictions/test_datarobot_gcp_storage_batch_scoring_dag.py
  tests/unit/_experimental/dags/predictions/test_datarobot_s3_batch_scoring_dag.py
  tests/unit/conftest.py
  tests/unit/hooks/credentials/__init__.py
  tests/unit/hooks/credentials/test_aws_credentials.py
  tests/unit/hooks/credentials/test_azure_credentials.py
  tests/unit/hooks/credentials/test_basic_credentials.py
  tests/unit/hooks/credentials/test_gcp_credentials.py
  tests/unit/hooks/credentials/test_oauth_credentials.py
  tests/unit/hooks/test_connections.py
  tests/unit/operators/test_ai_catalog.py
  tests/unit/operators/test_connections.py
  tests/unit/operators/test_credentials.py
Labels: Ready for Review

#206 [MODEL-17042] Add get model parameters operator and tests
  datarobot_provider/operators/model_training.py
  docs/autodoc_operators/operators_model_training.md
  tests/unit/operators/test_model_training.py
Labels: Ready for Review

#205 [MODEL-17059] Add segmentation task create operator, tests and docs
  datarobot_provider/operators/segmentation.py
  docs/autodoc_operators/operators_segmentation.md
  tests/unit/operators/test_segmentation.py
Labels: Ready for Review

#207 [MODEL-17053] Add CancelJobOperator
  datarobot_provider/operators/queue.py
  docs/autodoc_operators/operators_queue.md
  tests/unit/operators/test_queue.py
Labels: Ready for Review

#210 [MODEL-18291] Bump for release 0.3.0
  CHANGES.md
  datarobot_provider/__init__.py
  datarobot_provider/_version.py
Labels: 00 - Ready for Review

#211 [MODEL-18297] Update the default PR template
  .github/pull_request_template.md
  CHANGES.md
Labels: 00 - Ready for Review

#209 [MODEL-17056] Add operator to get jobs from queue
  datarobot_provider/operators/queue.py
  docs/autodoc_operators/operators_queue.md
  tests/unit/operators/test_queue.py
Labels: 00 - Ready for Review

#215 [MODEL-17047] Add cross validation operators
  CHANGES.md
  datarobot_provider/operators/model_training.py
  docs/autodoc_operators/operators_model_training.md
  tests/unit/operators/test_model_training.py
Labels: 00 - Ready for Review

#216 [MODEL-17048] Retrieve the features used to train a model
  CHANGES.md
  datarobot_provider/operators/model_insights.py
  docs/autodoc_operators/operators_insights.md
  tests/unit/operators/test_model_insights_job.py
Labels: 00 - Ready for Review

#217 [DM-17413] Move all MLData operators into `data_registry` and `data_prep` modules.
  CHANGES.md
  CODEOWNERS
  datarobot_provider/_experimental/deprecated_example_dags/advanced_datarobot_pipeline_jdbc_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_autopilot_options_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_create_project_from_ai_catalog_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_create_project_from_dataset_version_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_custom_model_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_custom_partitioning_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_dataset_upload_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_datetime_partitioning_pipeline_dag.py
  datarobot_provider/_experimental/deprecated_example_dags/datarobot_timeseries_pipeline_dag.py
  datarobot_provider/example_dags/dataprep_wrangler_autopilot.py
  datarobot_provider/example_dags/deployment_prediction_generation.py
  datarobot_provider/example_dags/featrue_discovery_retraining_and_scoring.py
  datarobot_provider/example_dags/feature_discovery_example.py
  datarobot_provider/example_dags/model_training_xgboost.py
  datarobot_provider/operators/connections.py
  datarobot_provider/operators/data_prep.py
  datarobot_provider/operators/data_registry.py
  datarobot_provider/operators/feature_discovery.py
  docs/autodoc_operators/operators_ai_catalog.md
  docs/autodoc_operators/operators_data_prep.md
  docs/autodoc_operators/operators_data_registry.md
  docs/autodoc_operators/operators_feature_discovery.md
  tests/unit/operators/test_ai_catalog.py
  tests/unit/operators/test_connections.py
  tests/unit/operators/test_data_prep.py
  tests/unit/operators/test_data_registry.py
  tests/unit/operators/test_feature_discovery.py
Labels: Ready for Review

#218 [MODEL-18335] Add GitHub release creation to mainline release pipeline
  .harness/release_early_access_pypi.yaml
Labels: 00 - Ready for Review

#212 [MODEL-17054] Update example docs for model training dag
  CHANGES.md
  docs/examples/model_training_xgboost.md
Labels: 00 - Ready for Review

#222 [MODEL-18375] Create automated release PR and Tag pipelines
  .harness/createreleasepr.yaml
  .harness/createreleasetag.yaml
  .harness/release_early_access_pypi.yaml
  .harness/release_pypi.yaml
  CHANGES.md
  README.md
  tests/unit/test_versions.py
Labels: 00 - Ready for Review

#223 [MODEL-18396] Add safety checks to release pipelines
  .harness/createreleasepr.yaml
  .harness/createreleasetag.yaml
  .harness/release_pypi.yaml
  .harness/templates/validate_commit_sha_1.yaml
  .harness/templates/validate_release_version_tag_1.yaml
  CHANGES.md
Labels: 00 - Ready for Review

#224 [RELEASE] Bump release for v0.4.1
  CHANGES.md
  datarobot_provider/__init__.py
  datarobot_provider/_version.py
Labels: Ready for Review, Auto Merge when Ready

#225 [-] Update readme related to release pipelines
  README.md
Labels: Ready for Review
