Repository datarobot/airflow-provider-datarobot, pull requests merged in 2025-01, with the labels that each got.

#96 [PRED-11010] Fix GetOrCreateCredentialOperator occurring when JDBCDataSourceHook is used.
  CODEOWNERS
  datarobot_provider/operators/credentials.py
  tests/unit/operators/test_credentials.py
Labels: 00 - Ready for Review

#97 [PRED-11010] Bump version to 0.0.10
  datarobot_provider/__init__.py
  setup.py
Labels: 00 - Ready for Review

#99 [MLDEV-1123] Add some additional help to the readme for starting a simple dev environment
  README.md
Labels: 00 - Ready for Review

#101 [MLDEV-1126] Improve makefile commands for astro dev environments
  .gitignore
  Makefile
  README.md
Labels: 00 - Ready for Review

#100 [MLDEV-1124] Update codeowners to have a more domain-oriented review process
  CODEOWNERS
Labels: 00 - Ready for Review

#103 [MLDEV-1130] Add pre-commit
  .pre-commit-config.yaml
  README.md
  requirements.txt
Labels: 00 - Ready for Review

#106 [MLDEV-1136] Get basic sphinx documentation up and running
  .gitignore
  CHANGES.md
  Makefile
  README.md
  datarobot_provider/_version.py
  docs/Makefile
  docs/_html/robots.txt
  docs/_static/css/tight_table.css
  docs/_templates/breadcrumbs.html
  docs/autodoc/api_reference.md
  docs/autodoc/operators_ai_catalog.md
  docs/autodoc/operators_autopilot.md
  docs/autodoc/operators_bias_and_fairness.md
  docs/autodoc/operators_connections.md
  docs/conf.py
  docs/index.md
  docs/latex_preamble.tex
  docs/reference/connections.md
  docs/reference/index.md
  docs/reference/installation.md
  docs/version.py
  requirements.txt
  setup.py
Labels: 00 - Ready for Review

#108 [PRED-11034] Move package configuration to pyproject.toml
  .harness/build_and_publish_pipy.yaml
  .harness/cichecks.yaml
  README.md
  datarobot_provider/hooks/connections.py
  datarobot_provider/hooks/credentials.py
  datarobot_provider/hooks/datarobot.py
  datarobot_provider/sensors/client.py
  pyproject.toml
  setup.py
Labels: 00 - Ready for Review, Close Jira on Merge

#111 [MLDEV-1133] Fix all mypy errors and enable mypy for PRs
  .harness/cichecks.yaml
  .mypy.ini
  .pre-commit-config.yaml
  CHANGES.md
  Makefile
  README.md
  datarobot_provider/example_dags/advanced_datarobot_pipeline_jdbc_dag.py
  datarobot_provider/example_dags/datarobot_jdbc_dynamic_dataset_dag.py
  datarobot_provider/example_dags/deployment_update_segment_analysis_settings_dag.py
  datarobot_provider/hooks/connections.py
  datarobot_provider/hooks/credentials.py
  datarobot_provider/hooks/datarobot.py
  datarobot_provider/operators/ai_catalog.py
  datarobot_provider/operators/autopilot.py
  datarobot_provider/operators/bias_and_fairness.py
  datarobot_provider/operators/connections.py
  datarobot_provider/operators/credentials.py
  datarobot_provider/operators/custom_models.py
  datarobot_provider/operators/datarobot.py
  datarobot_provider/operators/deployment.py
  datarobot_provider/operators/feature_discovery.py
  datarobot_provider/operators/mlops.py
  datarobot_provider/operators/model_insights.py
  datarobot_provider/operators/model_package.py
  datarobot_provider/operators/model_predictions.py
  datarobot_provider/operators/model_training.py
  datarobot_provider/operators/monitoring.py
  datarobot_provider/operators/monitoring_job.py
  datarobot_provider/operators/prediction_explanations.py
  datarobot_provider/operators/scoring_code.py
  datarobot_provider/operators/segment_analysis.py
  datarobot_provider/sensors/client.py
  datarobot_provider/sensors/datarobot.py
  datarobot_provider/sensors/model_insights.py
  datarobot_provider/sensors/model_training.py
  datarobot_provider/sensors/monitoring_job.py
  docs/reference/connections.md
  pyproject.toml
  tests/unit/operators/test_bias_and_fairness.py
Labels: Needs Review: MLDev, 00 - Ready for Review

#113 [-] Tweaks to mypy config and ignore error code additions
  datarobot_provider/hooks/credentials.py
  datarobot_provider/operators/credentials.py
  datarobot_provider/operators/datarobot.py
  datarobot_provider/operators/feature_discovery.py
  datarobot_provider/operators/monitoring.py
  pyproject.toml
Labels: Ready for Review

#105 [DM-16786] Add `CreateDatasetFromRecipeOperator`
  CHANGES.md
  datarobot_provider/operators/ai_catalog.py
  tests/unit/operators/test_ai_catalog.py
Labels: 00 - Ready for Review

#114 [MLDEV-1143] Spike: Add initial version of automated operator generation code and associated tests
  datarobot_provider/autogen/__init__.py
  datarobot_provider/autogen/generate_operator.py
  datarobot_provider/autogen/whitelist.yaml
  requirements.txt
  tests/conftest.py
  tests/fixtures/whitelist_test.yaml
  tests/fixtures/whitelist_test_output.txt
  tests/unit/autogen/__init__.py
  tests/unit/autogen/test_generate_operator.py
Labels: 00 - Ready for Review

#116 [DM-16787] Add `CreateWranglingRecipeOperator`
  CHANGES.md
  datarobot_provider/operators/ai_catalog.py
  tests/unit/operators/test_ai_catalog.py
Labels: 00 - Ready for Review

#117 [MLDEV-1178] Move existing dags to deprecated
  datarobot_provider/example_dags/deprecated/__init__.py
  datarobot_provider/example_dags/deprecated/advanced_datarobot_pipeline_jdbc_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_autopilot_options_pipeline_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_aws_s3_batch_scoring_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_azure_storage_batch_scoring_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_batch_monitoring_job_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_batch_scoring_templated_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_bigquery_batch_scoring_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_create_project_from_ai_catalog_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_create_project_from_dataset_version_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_custom_model_pipeline_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_custom_partitioning_pipeline_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_dataset_new_version_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_dataset_upload_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_datetime_partitioning_pipeline_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_external_model_pipeline_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_feature_discovery_pipeline_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_gcp_storage_batch_scoring_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_get_datastore_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_jdbc_batch_scoring_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_jdbc_dataset_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_jdbc_dynamic_dataset_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_pipeline_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_replace_custom_model_pipeline_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_score_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_timeseries_pipeline_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_upload_actuals_catalog_dag.py
  datarobot_provider/example_dags/deprecated/deployment_activate_deactivate_dag.py
  datarobot_provider/example_dags/deprecated/deployment_replace_model_dag.py
  datarobot_provider/example_dags/deprecated/deployment_service_stats_dag.py
  datarobot_provider/example_dags/deprecated/deployment_stat_and_accuracy_dag.py
  datarobot_provider/example_dags/deprecated/deployment_update_monitoring_settings_dag.py
  datarobot_provider/example_dags/deprecated/deployment_update_segment_analysis_settings_dag.py
  datarobot_provider/example_dags/deprecated/download_scoring_code_from_deployment_dag.py
  datarobot_provider/example_dags/deprecated/model_compute_insights_dag.py
  datarobot_provider/example_dags/deprecated/model_compute_prediction_explanations_dag.py
  datarobot_provider/example_dags/deprecated/model_compute_predictions_dag.py
  datarobot_provider/example_dags/deprecated/model_compute_shap_dag.py
  datarobot_provider/example_dags/deprecated/model_retrain_dag.py
  datarobot_provider/example_dags/deprecated/model_train_dag.py
  tests/unit/dags/pipline/test_datarobot_pipeline_dag.py
  tests/unit/dags/predictions/test_datarobot_azure_storage_batch_scoring_dag.py
  tests/unit/dags/predictions/test_datarobot_gcp_storage_batch_scoring_dag.py
  tests/unit/dags/predictions/test_datarobot_s3_batch_scoring_dag.py
  tests/unit/dags/predictions/test_datarobot_score_dag.py
  tests/unit/dags/project/test_create_project_from_ai_catalog_dag.py
  tests/unit/dags/project/test_create_project_from_dataset_version_dag.py
Labels: 00 - Ready for Review

#118 [DM-16785] Add `CreateFeatureDiscoveryRecipeOperator`
  datarobot_provider/operators/feature_discovery.py
  docs/autodoc/operators_feature_discovery.md
  tests/unit/operators/test_feature_discovery.py
Labels: 00 - Ready for Review

#119 [CFX-1398] Adding opt-in Airflow ruff checking
  datarobot_provider/example_dags/deprecated/datarobot_custom_model_pipeline_dag.py
  datarobot_provider/example_dags/deprecated/datarobot_replace_custom_model_pipeline_dag.py
  pyproject.toml
Labels: Ready for Review

#121 [CFX-1398] Misc airflow repo updates related to ruff linting
  datarobot_provider/hooks/connections.py
  datarobot_provider/hooks/credentials.py
  datarobot_provider/operators/ai_catalog.py
  datarobot_provider/operators/connections.py
  pyproject.toml
  tests/unit/hooks/credentials/test_aws_credentials.py
  tests/unit/hooks/credentials/test_azure_credentials.py
  tests/unit/hooks/credentials/test_basic_credentials.py
  tests/unit/hooks/credentials/test_gcp_credentials.py
  tests/unit/hooks/credentials/test_oauth_credentials.py
Labels: Ready for Review, Auto Merge on Green

#124 [MLDEV-1189] Add very basic hospital readmissions dag that we can build from
  datarobot_provider/example_dags/hospital_readmissions_example.py
Labels: 00 - Ready for Review

#123 [DM-16784] Add a GetDataStoreOperator
  .harness/cichecks.yaml
  CHANGES.md
  datarobot_provider/operators/ai_catalog.py
  datarobot_provider/operators/connections.py
  pyproject.toml
  tests/unit/operators/test_ai_catalog.py
  tests/unit/operators/test_connections.py
Labels: 00 - Ready for Review

#126 [MLDEV-1174] Add use case create operator
  datarobot_provider/operators/datarobot.py
  docs/autodoc/operators_datarobot.md
  tests/unit/operators/test_datarobot.py
Labels: 00 - Ready for Review
